// Auto-generated by OpenLane
module counter(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst,
  input csb00,
  input csb01,
  input[7:0] addr00,
  input[7:0] addr01,
  input[15:0] din00,
  input[15:0] din01,
  output[15:0] sine_out
);
endmodule
