// Auto-generated by OpenLane
module counter(
`ifdef USE_POWER_PINS
  inout vccd1,
  inout vssd1,
`endif
  input clk,
  input rst,
  input csb0,
  input[7:0] addr0,
  input[15:0] din0,
  output[15:0] sine_out
);
endmodule
