/* Generated by Yosys 0.46 (git sha1 e97731b9dda91fa5fa53ed87df7c34163ba59a41, clang++ 17.0.6 -fPIC -O3) */

module counter(clk, rst, csb00, csb01, addr00, addr01, din00, din01, sine_out);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  input [7:0] addr00;
  wire [7:0] addr00;
  input [7:0] addr01;
  wire [7:0] addr01;
  input clk;
  wire clk;
  input csb00;
  wire csb00;
  input csb01;
  wire csb01;
  input [15:0] din00;
  wire [15:0] din00;
  input [15:0] din01;
  wire [15:0] din01;
  input rst;
  wire rst;
  output [15:0] sine_out;
  wire [15:0] sine_out;
  wire \sine_out_temp0[0] ;
  wire \sine_out_temp0[10] ;
  wire \sine_out_temp0[11] ;
  wire \sine_out_temp0[12] ;
  wire \sine_out_temp0[13] ;
  wire \sine_out_temp0[14] ;
  wire \sine_out_temp0[15] ;
  wire \sine_out_temp0[1] ;
  wire \sine_out_temp0[2] ;
  wire \sine_out_temp0[3] ;
  wire \sine_out_temp0[4] ;
  wire \sine_out_temp0[5] ;
  wire \sine_out_temp0[6] ;
  wire \sine_out_temp0[7] ;
  wire \sine_out_temp0[8] ;
  wire \sine_out_temp0[9] ;
  wire \sine_out_temp1[0] ;
  wire \sine_out_temp1[10] ;
  wire \sine_out_temp1[11] ;
  wire \sine_out_temp1[12] ;
  wire \sine_out_temp1[13] ;
  wire \sine_out_temp1[14] ;
  wire \sine_out_temp1[15] ;
  wire \sine_out_temp1[1] ;
  wire \sine_out_temp1[2] ;
  wire \sine_out_temp1[3] ;
  wire \sine_out_temp1[4] ;
  wire \sine_out_temp1[5] ;
  wire \sine_out_temp1[6] ;
  wire \sine_out_temp1[7] ;
  wire \sine_out_temp1[8] ;
  wire \sine_out_temp1[9] ;
  wire \tcout[0] ;
  wire \tcout[1] ;
  wire \tcout[2] ;
  wire \tcout[3] ;
  wire \tcout[4] ;
  wire \tcout[5] ;
  wire \tcout[6] ;
  wire \tcout[7] ;
  wire \tcout[8] ;
  sky130_fd_sc_hd__inv_2 _061_ (
    .A(\tcout[0] ),
    .Y(_016_)
  );
  sky130_fd_sc_hd__inv_2 _062_ (
    .A(rst),
    .Y(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _063_ (
    .A0(\sine_out_temp0[0] ),
    .A1(\sine_out_temp1[0] ),
    .S(\tcout[8] ),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _064_ (
    .A0(\sine_out_temp0[1] ),
    .A1(\sine_out_temp1[1] ),
    .S(\tcout[8] ),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _065_ (
    .A0(\sine_out_temp0[2] ),
    .A1(\sine_out_temp1[2] ),
    .S(\tcout[8] ),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _066_ (
    .A0(\sine_out_temp0[3] ),
    .A1(\sine_out_temp1[3] ),
    .S(\tcout[8] ),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _067_ (
    .A0(\sine_out_temp0[4] ),
    .A1(\sine_out_temp1[4] ),
    .S(\tcout[8] ),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _068_ (
    .A0(\sine_out_temp0[5] ),
    .A1(\sine_out_temp1[5] ),
    .S(\tcout[8] ),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _069_ (
    .A0(\sine_out_temp0[6] ),
    .A1(\sine_out_temp1[6] ),
    .S(\tcout[8] ),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _070_ (
    .A0(\sine_out_temp0[7] ),
    .A1(\sine_out_temp1[7] ),
    .S(\tcout[8] ),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _071_ (
    .A0(\sine_out_temp0[8] ),
    .A1(\sine_out_temp1[8] ),
    .S(\tcout[8] ),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _072_ (
    .A0(\sine_out_temp0[9] ),
    .A1(\sine_out_temp1[9] ),
    .S(\tcout[8] ),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _073_ (
    .A0(\sine_out_temp0[10] ),
    .A1(\sine_out_temp1[10] ),
    .S(\tcout[8] ),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _074_ (
    .A0(\sine_out_temp0[11] ),
    .A1(\sine_out_temp1[11] ),
    .S(\tcout[8] ),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _075_ (
    .A0(\sine_out_temp0[12] ),
    .A1(\sine_out_temp1[12] ),
    .S(\tcout[8] ),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _076_ (
    .A0(\sine_out_temp0[13] ),
    .A1(\sine_out_temp1[13] ),
    .S(\tcout[8] ),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _077_ (
    .A0(\sine_out_temp0[14] ),
    .A1(\sine_out_temp1[14] ),
    .S(\tcout[8] ),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _078_ (
    .A0(\sine_out_temp0[15] ),
    .A1(\sine_out_temp1[15] ),
    .S(\tcout[8] ),
    .X(_006_)
  );
  sky130_fd_sc_hd__xor2_2 _079_ (
    .A(\tcout[0] ),
    .B(\tcout[1] ),
    .X(_017_)
  );
  sky130_fd_sc_hd__and3_2 _080_ (
    .A(\tcout[0] ),
    .B(\tcout[1] ),
    .C(\tcout[2] ),
    .X(_050_)
  );
  sky130_fd_sc_hd__a21oi_2 _081_ (
    .A1(\tcout[0] ),
    .A2(\tcout[1] ),
    .B1(\tcout[2] ),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_2 _082_ (
    .A(_050_),
    .B(_051_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__and4_2 _083_ (
    .A(\tcout[0] ),
    .B(\tcout[1] ),
    .C(\tcout[2] ),
    .D(\tcout[3] ),
    .X(_052_)
  );
  sky130_fd_sc_hd__nor2_2 _084_ (
    .A(\tcout[3] ),
    .B(_050_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_2 _085_ (
    .A(_052_),
    .B(_053_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__xor2_2 _086_ (
    .A(\tcout[4] ),
    .B(_052_),
    .X(_020_)
  );
  sky130_fd_sc_hd__and3_2 _087_ (
    .A(\tcout[4] ),
    .B(\tcout[5] ),
    .C(_052_),
    .X(_054_)
  );
  sky130_fd_sc_hd__a21oi_2 _088_ (
    .A1(\tcout[4] ),
    .A2(_052_),
    .B1(\tcout[5] ),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_2 _089_ (
    .A(_054_),
    .B(_055_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__xor2_2 _090_ (
    .A(\tcout[6] ),
    .B(_054_),
    .X(_022_)
  );
  sky130_fd_sc_hd__and2_2 _091_ (
    .A(\tcout[6] ),
    .B(\tcout[7] ),
    .X(_056_)
  );
  sky130_fd_sc_hd__and4_2 _092_ (
    .A(\tcout[4] ),
    .B(\tcout[5] ),
    .C(_052_),
    .D(_056_),
    .X(_057_)
  );
  sky130_fd_sc_hd__a41o_2 _093_ (
    .A1(\tcout[4] ),
    .A2(\tcout[5] ),
    .A3(\tcout[6] ),
    .A4(_052_),
    .B1(\tcout[7] ),
    .X(_058_)
  );
  sky130_fd_sc_hd__and2b_2 _094_ (
    .A_N(_057_),
    .B(_058_),
    .X(_023_)
  );
  sky130_fd_sc_hd__xor2_2 _095_ (
    .A(\tcout[8] ),
    .B(_057_),
    .X(_024_)
  );
  sky130_fd_sc_hd__inv_2 _096_ (
    .A(rst),
    .Y(_026_)
  );
  sky130_fd_sc_hd__inv_2 _097_ (
    .A(rst),
    .Y(_027_)
  );
  sky130_fd_sc_hd__inv_2 _098_ (
    .A(rst),
    .Y(_028_)
  );
  sky130_fd_sc_hd__inv_2 _099_ (
    .A(rst),
    .Y(_029_)
  );
  sky130_fd_sc_hd__inv_2 _100_ (
    .A(rst),
    .Y(_030_)
  );
  sky130_fd_sc_hd__inv_2 _101_ (
    .A(rst),
    .Y(_031_)
  );
  sky130_fd_sc_hd__inv_2 _102_ (
    .A(rst),
    .Y(_032_)
  );
  sky130_fd_sc_hd__inv_2 _103_ (
    .A(rst),
    .Y(_033_)
  );
  sky130_fd_sc_hd__inv_2 _104_ (
    .A(rst),
    .Y(_034_)
  );
  sky130_fd_sc_hd__inv_2 _105_ (
    .A(rst),
    .Y(_035_)
  );
  sky130_fd_sc_hd__inv_2 _106_ (
    .A(rst),
    .Y(_036_)
  );
  sky130_fd_sc_hd__inv_2 _107_ (
    .A(rst),
    .Y(_037_)
  );
  sky130_fd_sc_hd__inv_2 _108_ (
    .A(rst),
    .Y(_038_)
  );
  sky130_fd_sc_hd__inv_2 _109_ (
    .A(rst),
    .Y(_039_)
  );
  sky130_fd_sc_hd__inv_2 _110_ (
    .A(rst),
    .Y(_040_)
  );
  sky130_fd_sc_hd__inv_2 _111_ (
    .A(rst),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_2 _112_ (
    .A(rst),
    .Y(_042_)
  );
  sky130_fd_sc_hd__inv_2 _113_ (
    .A(rst),
    .Y(_043_)
  );
  sky130_fd_sc_hd__inv_2 _114_ (
    .A(rst),
    .Y(_044_)
  );
  sky130_fd_sc_hd__inv_2 _115_ (
    .A(rst),
    .Y(_045_)
  );
  sky130_fd_sc_hd__inv_2 _116_ (
    .A(rst),
    .Y(_046_)
  );
  sky130_fd_sc_hd__inv_2 _117_ (
    .A(rst),
    .Y(_047_)
  );
  sky130_fd_sc_hd__inv_2 _118_ (
    .A(rst),
    .Y(_048_)
  );
  sky130_fd_sc_hd__inv_2 _119_ (
    .A(rst),
    .Y(_049_)
  );
  sky130_fd_sc_hd__dfrtp_2 _120_ (
    .CLK(clk),
    .D(_014_),
    .Q(sine_out[8]),
    .RESET_B(_025_)
  );
  sky130_fd_sc_hd__dfrtp_2 _121_ (
    .CLK(clk),
    .D(_015_),
    .Q(sine_out[9]),
    .RESET_B(_026_)
  );
  sky130_fd_sc_hd__dfrtp_2 _122_ (
    .CLK(clk),
    .D(_001_),
    .Q(sine_out[10]),
    .RESET_B(_027_)
  );
  sky130_fd_sc_hd__dfrtp_2 _123_ (
    .CLK(clk),
    .D(_002_),
    .Q(sine_out[11]),
    .RESET_B(_028_)
  );
  sky130_fd_sc_hd__dfrtp_2 _124_ (
    .CLK(clk),
    .D(_003_),
    .Q(sine_out[12]),
    .RESET_B(_029_)
  );
  sky130_fd_sc_hd__dfrtp_2 _125_ (
    .CLK(clk),
    .D(_004_),
    .Q(sine_out[13]),
    .RESET_B(_030_)
  );
  sky130_fd_sc_hd__dfrtp_2 _126_ (
    .CLK(clk),
    .D(_005_),
    .Q(sine_out[14]),
    .RESET_B(_031_)
  );
  sky130_fd_sc_hd__dfrtp_2 _127_ (
    .CLK(clk),
    .D(_006_),
    .Q(sine_out[15]),
    .RESET_B(_032_)
  );
  sky130_fd_sc_hd__dfrtp_2 _128_ (
    .CLK(clk),
    .D(_016_),
    .Q(\tcout[0] ),
    .RESET_B(_033_)
  );
  sky130_fd_sc_hd__dfrtp_2 _129_ (
    .CLK(clk),
    .D(_017_),
    .Q(\tcout[1] ),
    .RESET_B(_034_)
  );
  sky130_fd_sc_hd__dfrtp_2 _130_ (
    .CLK(clk),
    .D(_018_),
    .Q(\tcout[2] ),
    .RESET_B(_035_)
  );
  sky130_fd_sc_hd__dfrtp_2 _131_ (
    .CLK(clk),
    .D(_019_),
    .Q(\tcout[3] ),
    .RESET_B(_036_)
  );
  sky130_fd_sc_hd__dfrtp_2 _132_ (
    .CLK(clk),
    .D(_020_),
    .Q(\tcout[4] ),
    .RESET_B(_037_)
  );
  sky130_fd_sc_hd__dfrtp_2 _133_ (
    .CLK(clk),
    .D(_021_),
    .Q(\tcout[5] ),
    .RESET_B(_038_)
  );
  sky130_fd_sc_hd__dfrtp_2 _134_ (
    .CLK(clk),
    .D(_022_),
    .Q(\tcout[6] ),
    .RESET_B(_039_)
  );
  sky130_fd_sc_hd__dfrtp_2 _135_ (
    .CLK(clk),
    .D(_023_),
    .Q(\tcout[7] ),
    .RESET_B(_040_)
  );
  sky130_fd_sc_hd__dfrtp_2 _136_ (
    .CLK(clk),
    .D(_024_),
    .Q(\tcout[8] ),
    .RESET_B(_041_)
  );
  sky130_fd_sc_hd__dfrtp_2 _137_ (
    .CLK(clk),
    .D(_000_),
    .Q(sine_out[0]),
    .RESET_B(_042_)
  );
  sky130_fd_sc_hd__dfrtp_2 _138_ (
    .CLK(clk),
    .D(_007_),
    .Q(sine_out[1]),
    .RESET_B(_043_)
  );
  sky130_fd_sc_hd__dfrtp_2 _139_ (
    .CLK(clk),
    .D(_008_),
    .Q(sine_out[2]),
    .RESET_B(_044_)
  );
  sky130_fd_sc_hd__dfrtp_2 _140_ (
    .CLK(clk),
    .D(_009_),
    .Q(sine_out[3]),
    .RESET_B(_045_)
  );
  sky130_fd_sc_hd__dfrtp_2 _141_ (
    .CLK(clk),
    .D(_010_),
    .Q(sine_out[4]),
    .RESET_B(_046_)
  );
  sky130_fd_sc_hd__dfrtp_2 _142_ (
    .CLK(clk),
    .D(_011_),
    .Q(sine_out[5]),
    .RESET_B(_047_)
  );
  sky130_fd_sc_hd__dfrtp_2 _143_ (
    .CLK(clk),
    .D(_012_),
    .Q(sine_out[6]),
    .RESET_B(_048_)
  );
  sky130_fd_sc_hd__dfrtp_2 _144_ (
    .CLK(clk),
    .D(_013_),
    .Q(sine_out[7]),
    .RESET_B(_049_)
  );
  sky130_fd_sc_hd__conb_1 _145_ (
    .LO(_059_)
  );
  sky130_fd_sc_hd__conb_1 _146_ (
    .LO(_060_)
  );
  ram_256x16 mem_i0 (
    .addr0(addr00),
    .addr1({ \tcout[7] , \tcout[6] , \tcout[5] , \tcout[4] , \tcout[3] , \tcout[2] , \tcout[1] , \tcout[0]  }),
    .clk0(clk),
    .clk1(clk),
    .csb0(csb00),
    .csb1(_059_),
    .din0(din00),
    .dout1({ \sine_out_temp0[15] , \sine_out_temp0[14] , \sine_out_temp0[13] , \sine_out_temp0[12] , \sine_out_temp0[11] , \sine_out_temp0[10] , \sine_out_temp0[9] , \sine_out_temp0[8] , \sine_out_temp0[7] , \sine_out_temp0[6] , \sine_out_temp0[5] , \sine_out_temp0[4] , \sine_out_temp0[3] , \sine_out_temp0[2] , \sine_out_temp0[1] , \sine_out_temp0[0]  })
  );
  ram_256x16 mem_i1 (
    .addr0(addr01),
    .addr1({ \tcout[7] , \tcout[6] , \tcout[5] , \tcout[4] , \tcout[3] , \tcout[2] , \tcout[1] , \tcout[0]  }),
    .clk0(clk),
    .clk1(clk),
    .csb0(csb01),
    .csb1(_060_),
    .din0(din01),
    .dout1({ \sine_out_temp1[15] , \sine_out_temp1[14] , \sine_out_temp1[13] , \sine_out_temp1[12] , \sine_out_temp1[11] , \sine_out_temp1[10] , \sine_out_temp1[9] , \sine_out_temp1[8] , \sine_out_temp1[7] , \sine_out_temp1[6] , \sine_out_temp1[5] , \sine_out_temp1[4] , \sine_out_temp1[3] , \sine_out_temp1[2] , \sine_out_temp1[1] , \sine_out_temp1[0]  })
  );
endmodule
